from bs4 import BeautifulSoup
import requests 
import os

output_dir = os.path.join("Output", "Validation")
save_path = os.path.join("Output", "Validation", "data")

# Making output directories
# Check if the directory already exists
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
if not os.path.exists(save_path):
    os.mkdir(save_path)

url = "https://www.rcsb.org/experimental/"

# list of pdbs to import taken from pdb_names generated by "get_pdb_names.R"
with open("Output/pdb_names.txt", "r") as file:
    # Skip the first line which contains the column name
    next(file)
    # Initialize an empty list to store the names
    pdb = []
    # Iterate over the lines in the file
    for line in file:
        # Strip any leading/trailing whitespaces and append the name to the list
        pdb.append(line.strip())

# Initialising list to store PDBs that are missing Q-score data
missing_validation = []

for i in pdb:
    # adding pdb to the URL search
    pdb_query = url + i

    # Reading in PDB HTML page
    response = requests.get(pdb_query)
    doc = BeautifulSoup(response.text, "html.parser")

    try:
        # Finding the validation data link by searching for the anchor tag with the specific string
        validation_link = doc.find("a", string="Validation (XML - gz)")
        
        if validation_link:
            validation_url = validation_link.get('href')
            if validation_url.startswith("//"):
                validation_url = "https:" + validation_url
            print("Validation link found:", validation_url)

            # Download the file
            file_response = requests.get(validation_url)
            file_name = os.path.join(save_path, validation_url.split("/")[-1])

            with open(file_name, 'wb') as file:
                file.write(file_response.content)
        
        else:
            print("Validation link not found")
            missing_validation.append(i)

    except AttributeError:
        print("Error finding validation link")
        missing_validation.append(i)

### Adding PDBs to excluded list ###
excluded_file = os.path.join("Output", "excluded_list.txt")
file_exists = os.path.exists(excluded_file) # Check if file exists

# Getting a list of pdbs already added to exclusion list to avoid duplicate entries
existing_pdbs = set()
if file_exists:
    with open(excluded_file, "r") as f:
        for line in f:
            if line.strip() and not line.startswith("PDB ID"):
                existing_pdbs.add(line.split("\t")[0])  # Get PDB ID before first tab

# Adding missing PDBs with missing Q-scores to excluded list
if missing_validation:
    with open(excluded_file, "a") as f:
        # Write header only if the file didn't exist before
        if not file_exists:
            f.write("PDB ID\tReason\n")

        # Write your excluded entries
        for pdb in missing_validation:
            if pdb not in existing_pdbs:    
                line = f"{pdb}\tQ-Score data not found\n"
                f.write(line)
else:
    print("\n🎉 All PDBs have validation data! No failures found.")

